version: '3.5'

services:
  project:
    build:
      context: .
      dockerfile: src/project/Dockerfile
    image: project
    container_name: project
    networks:
      - instrument
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped

networks:
  instrument:
    ipam:
      driver: default
      config:
        - subnet: 172.19.5.1/27
