#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Generalized instrument that services commands generated by clients over
variuos protocols (MQTT, OPC UA).
"""
import logging
from lib import helper_functions

__author__ = "Brent Maranzano"
__license__ = "MIT"


logger = logging.getLogger(__name__)



