#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
OPC request handler
"""
import logging
from pdb import set_trace

__author__ = "Brent Maranzano"
__license__ = "MIT"


logger = logging.getLogger("instrument.projects.ape")


def process_request(node, val, data):
    """Process requests generated by the node changes from the OPC service.

    Arguments
    node (str): Browse name of originating node.
    value (varries): Value of the node

    returns response object
    """
    browse_name = str(node.get_browse_name())
    if "WATCHDOG_CONTROLLER" in browse_name:
        return {"node": "WATCHDOG_INSTRUMENT", "value": val}
    elif "START" in browse_name:
        pass
    elif "STOP" in browse_name:
        pass
    elif "SETFLOW_CONTROLLER" in browse_name:
        pass
